// Importing the `createSlice` function from the `@reduxjs/toolkit` package
import { createSlice } from "@reduxjs/toolkit";

// Creating a slice of state named `home` using the `createSlice` function
export const homeSlice = createSlice({
    // Specifying the name of the slice
    name: "home",
    // Setting the initial state for the slice
    initialState: {
        url: {},    // Initial state for storing API configurations
        genres: {}, // Initial state for storing genre data
    },
    // Defining reducers to handle state mutations
    reducers: {
        // Reducer to update `url` state with API configuration data
        getApiConfiguration: (state, action) => {
            state.url = action.payload; // Updating `url` state with payload data
        },
        // Reducer to update `genres` state with genre data
        getGenres: (state, action) => {
            state.genres = action.payload; // Updating `genres` state with payload data
        },
    },
});

// Action creators are generated for each case reducer function
export const { getApiConfiguration, getGenres } = homeSlice.actions;

// Exporting the reducer function generated by `createSlice`
export default homeSlice.reducer;
